version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx1600m
    steps:
      - run: echo 'export ANDROID_NDK_HOME=$ANDROID_NDK' >> $BASH_ENV
      - checkout:
          post:
            - mkdir $ANDROID_HOME/liceses/ && cp .circleci/android-sdk-licenses $ANDROID_HOME/licenses/
            - cp .circleci/gradle.properties $HOME/
      - run: echo $ANDROID_NDK_HOME
      - run: echo $ANDROID_HOME
      - run: ls -alt $ANDROID_HOME
      - run: ls -alt /opt/android/
      - run: if [[ ! -e android-ndk-r14b ]]; then wget https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip && unzip android-ndk-r14b-linux-x86_64.zip; fi
      - run: echo 'export ANDROID_NDK_HOME=android-ndk-r14b' >> $BASH_ENV
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "samples/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "samples/build.gradle" }}
      - run:
          name: Run build
          command: ./gradlew assembleRelease assembleDebug
      - store_artifacts:
          path: samples/build/outputs
          destination: reports
      # - store_test_results:
      #     path: samples/build/test-results
