version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx1600m
    steps:
      - run:
          name: Set ANDROID_NDK_HOME, why dont you exported it yet?
          command: run: echo 'export ANDROID_NDK_HOME=${ANDROID_NDK}' >> $BASH_ENV
      - checkout:
          post:
            - mkdir $ANDROID_HOME/liceses/ && cp .circleci/android-sdk-licenses $ANDROID_HOME/licenses/
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "samples/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "samples/build.gradle" }}
      - run:
          name: Run build
          command: ./gradlew assembleRelease assembleDebug
      - store_artifacts:
          path: samples/build/outputs
          destination: reports
      # - store_test_results:
      #     path: samples/build/test-results
